[package]
name = "ROT"
version = "0.1.0"
authors = ["root"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rot13 = "0.1.1"
base64 = "0.12.3"
